// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTJFwqrt-2n6lP3g1aVoB3n7py-4WlosE',
    appId: '1:526922532314:web:b7aaa5a6b1335932de6ce3',
    messagingSenderId: '526922532314',
    projectId: 'mba22-564ab',
    authDomain: 'mba22-564ab.firebaseapp.com',
    storageBucket: 'mba22-564ab.appspot.com',
    measurementId: 'G-VQEE0933KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPt-cfzZ-DmeU7ezDdif1kATYIoTV-m8g',
    appId: '1:526922532314:android:49992a7099454f35de6ce3',
    messagingSenderId: '526922532314',
    projectId: 'mba22-564ab',
    storageBucket: 'mba22-564ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD4g6dvPnFId-xSRehTmuM_CtJDMaGXA4',
    appId: '1:526922532314:ios:626ab47f418e3d65de6ce3',
    messagingSenderId: '526922532314',
    projectId: 'mba22-564ab',
    storageBucket: 'mba22-564ab.appspot.com',
    iosClientId: '526922532314-d61h5l0sefitc97oli04hjheffg6pi03.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD4g6dvPnFId-xSRehTmuM_CtJDMaGXA4',
    appId: '1:526922532314:ios:626ab47f418e3d65de6ce3',
    messagingSenderId: '526922532314',
    projectId: 'mba22-564ab',
    storageBucket: 'mba22-564ab.appspot.com',
    iosClientId: '526922532314-d61h5l0sefitc97oli04hjheffg6pi03.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
